### ISSUE TITLE
Automatic or Manual

### ISSUE THREAD

**Issue by B0j4ngl35** [HuskyDG/Magisk_BootloopSaver#1]
I've noticed that this module automatically detects if I get into bootloop (zygote keep restart). What I do not understand is whether or 
not this module [automatically] disables all modules and restarts the system because the description of your module does not state that.

**Comment by HuskyDG** [comment]
It's automatically, this module will detect if your boot process keep restart the zygote many time in 50s, then it will disable all module and restart the system
